$stdout.sync = true

require "mcptask_runner/version"
require "mcptask_runner/version_manager"
require "mcptask_runner/logger"
require "mcptask_runner/snapshot_builder"
require "mcptask_runner/claude_md"
require "mcptask_runner/run_log"
require "mcptask_runner/services/workflow_steps"
require "mcptask_runner/services/claude_code_base"
require "mcptask_runner/services/claude_code/honest"
require "mcptask_runner/services/claude_code/dry"
require "mcptask_runner/services/claude_code/triage"
require "mcptask_runner/services/claude_code/review"
require "mcptask_runner/services/claude_code/reviews"
require "mcptask_runner/services/claude_code/story_manual"
require "mcptask_runner/services/claude_code/story_auto_squash"
require "mcptask_runner/services/claude_code/next_task_auto_squash"
require "mcptask_runner/services/claude_code/today_auto_squash"
require "mcptask_runner/services/claude_code/queue_auto_squash"
require "mcptask_runner/services/claude_code/once_auto_squash"
require "mcptask_runner/services/claude_code/task_manual"
require "mcptask_runner/services/claude_code/task_auto_squash"
require "mcptask_runner/services/approval_collector"
require "mcptask_runner/services/permission_syncer"
require "mcptask_runner/services/work_loop"
require "mcptask_runner/services/time_status_client"
require "mcptask_runner/services/quota_guard"
require "mcptask_runner/services/concerns/mcptask_piece_rest"
require "mcptask_runner/services/bug_reporter"
require "mcptask_runner/services/runner_error_reporter"
require "mcptask_runner/services/skill_installer"
require "mcptask_runner/services/installer"
require "mcptask_runner/services/updater"
require "mcptask_runner/services/decider"
require "mcptask_runner/services/daily_scheduler"
require "mcptask_runner/services/waiting_strategy"
require "mcptask_runner/services/concerns/bug_destination_config"
require "mcptask_runner/services/concerns/waiting_strategy_config"
require "mcptask_runner/services/concerns/pr_template_config"
require "mcptask_runner/event_stream"
require "mcptask_runner/railtie"

module McptaskRunner
  class Error < StandardError; end
end
